"""
Comparison PDF report generator for ResumeIQ.
Generates a professional A4 PDF with bar chart visualization and diff analysis.
"""

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor


def _draw_comparison_bar_chart(c, x, y, width, before, after, label="ATS Score"):
    """Draw a horizontal before/after bar chart comparison."""
    bar_height = 16
    gap = 6

    # Title
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(HexColor("#0f172a"))
    c.drawString(x, y, label)
    y -= 22

    # Before bar
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#64748b"))
    c.drawString(x, y + 4, f"V1 (Before): {before}")
    y -= 18

    # Background
    c.setFillColor(HexColor("#e5e7eb"))
    c.roundRect(x, y, width, bar_height, 6, fill=1, stroke=0)
    # Fill
    fill_w = (before / 100) * width if before > 0 else 0
    c.setFillColor(HexColor("#fb923c"))
    if fill_w > 0:
        c.roundRect(x, y, fill_w, bar_height, 6, fill=1, stroke=0)
    y -= bar_height + gap + 4

    # After bar
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#64748b"))
    c.drawString(x, y + 4, f"V2 (After): {after}")
    y -= 18

    c.setFillColor(HexColor("#e5e7eb"))
    c.roundRect(x, y, width, bar_height, 6, fill=1, stroke=0)
    fill_w = (after / 100) * width if after > 0 else 0
    c.setFillColor(HexColor("#6366f1"))
    if fill_w > 0:
        c.roundRect(x, y, fill_w, bar_height, 6, fill=1, stroke=0)

    c.setFillColor(HexColor("#000000"))
    return y - 30


def generate_comparison_pdf(comparison, filepath):
    """
    Generate a comparison report PDF with bar chart visualization.

    Args:
        comparison: dict with keys role, ats_before, ats_after, ats_change,
                    skills_added, skills_removed, jd_before, jd_after, ai_summary.
        filepath:   absolute path to write the PDF to.
    """
    c = canvas.Canvas(filepath, pagesize=A4)
    width, height = A4
    y = height - 50

    # ── Title ──
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "Resume Comparison Report")
    y -= 22

    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#64748b"))
    c.drawString(50, y, "Generated by ResumeIQ")
    c.setFillColor(HexColor("#000000"))
    y -= 30

    # ── Role ──
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, f"Target Role: {comparison['role']}")
    y -= 30

    # ── ATS Score Bar Chart ──
    y = _draw_comparison_bar_chart(
        c, 70, y, 350,
        comparison["ats_before"],
        comparison["ats_after"],
        "ATS Score Comparison"
    )

    # ── ATS Change Summary ──
    change = comparison["ats_change"]
    c.setFont("Helvetica-Bold", 11)
    if change > 0:
        c.setFillColor(HexColor("#16a34a"))
        change_text = f"↑ Improvement: +{change} points"
    elif change < 0:
        c.setFillColor(HexColor("#dc2626"))
        change_text = f"↓ Declined: {change} points"
    else:
        c.setFillColor(HexColor("#64748b"))
        change_text = "→ No change in score"

    c.drawString(70, y, change_text)
    c.setFillColor(HexColor("#000000"))
    y -= 30

    # ── Skills Added ──
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Skills Added:")
    y -= 18

    c.setFont("Helvetica", 10)
    added = comparison.get("skills_added", [])
    if added:
        for skill in added:
            if y < 60:
                break
            c.setFillColor(HexColor("#16a34a"))
            c.drawString(70, y, f"+ {skill}")
            y -= 14
    else:
        c.setFillColor(HexColor("#64748b"))
        c.drawString(70, y, "No new skills added")
        y -= 14

    c.setFillColor(HexColor("#000000"))
    y -= 12

    # ── Skills Removed ──
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Skills Removed:")
    y -= 18

    c.setFont("Helvetica", 10)
    removed = comparison.get("skills_removed", [])
    if removed:
        for skill in removed:
            if y < 60:
                break
            c.setFillColor(HexColor("#dc2626"))
            c.drawString(70, y, f"- {skill}")
            y -= 14
    else:
        c.setFillColor(HexColor("#64748b"))
        c.drawString(70, y, "No skills removed")
        y -= 14

    c.setFillColor(HexColor("#000000"))
    y -= 12

    # ── JD Match (if available) ──
    jd_before = comparison.get("jd_before")
    jd_after = comparison.get("jd_after")
    if jd_before and jd_after and y > 80:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Job Description Match:")
        y -= 18

        c.setFont("Helvetica", 10)
        c.drawString(70, y, f"Before: {jd_before.get('match_percentage', 0)}%")
        y -= 16
        c.drawString(70, y, f"After:  {jd_after.get('match_percentage', 0)}%")
        y -= 20

    # ── AI Insight ──
    if y > 100:
        y -= 6
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "AI Insight")
        y -= 18

        c.setFont("Helvetica", 10)
        ai_summary = comparison.get("ai_summary", "")
        if not ai_summary:
            # Fallback to generated insight
            role = comparison.get("role", "the target")
            if change > 0:
                ai_summary = (
                    f"The updated resume demonstrates improved alignment with {role} role "
                    f"requirements, reflecting stronger keyword coverage and domain-relevant "
                    f"skill inclusion."
                )
            elif change < 0:
                ai_summary = (
                    f"The updated resume shows reduced alignment with the {role} role, "
                    f"possibly due to removal of key skills or reduced keyword relevance."
                )
            else:
                ai_summary = (
                    f"Both resume versions demonstrate similar alignment with the "
                    f"{role} role requirements."
                )

        # Word-wrap
        words = ai_summary.split()
        lines = []
        current = ""
        for w in words:
            if len(current) + len(w) + 1 > 88:
                lines.append(current)
                current = w
            else:
                current = f"{current} {w}" if current else w
        if current:
            lines.append(current)

        for line in lines[:5]:
            if y < 60:
                break
            c.drawString(70, y, line)
            y -= 14

    c.save()
