"""
Full-feature PDF report generator for ResumeIQ.
Generates a professional A4 PDF with ATS donut chart, breakdown, JD match,
resume insights, AI suggestions, and career roadmap — matching result.html parity.
"""

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
import math


def _draw_donut_chart(c, cx, cy, radius, score, label="ATS Score"):
    """Draw a donut chart centered at (cx, cy) showing the ATS score."""
    outer = radius
    inner = radius * 0.65

    # Background ring
    c.setFillColor(HexColor("#e2e8f0"))
    c.setStrokeColor(HexColor("#e2e8f0"))
    c.circle(cx, cy, outer, fill=1, stroke=0)
    c.setFillColor(HexColor("#ffffff"))
    c.circle(cx, cy, inner, fill=1, stroke=0)

    # Score arc
    if score > 0:
        if score >= 80:
            color = HexColor("#14b8a6")
        elif score >= 60:
            color = HexColor("#6366f1")
        else:
            color = HexColor("#ef4444")

        start_angle = 90
        sweep = -(score / 100) * 360

        c.setFillColor(color)
        c.setStrokeColor(color)

        # Draw pie wedge then cut out inner circle
        p = c.beginPath()
        p.moveTo(cx, cy)
        p.arcTo(cx - outer, cy - outer, cx + outer, cy + outer,
                start_angle, sweep)
        p.close()
        c.drawPath(p, fill=1, stroke=0)

        # Cut out center
        c.setFillColor(HexColor("#ffffff"))
        c.circle(cx, cy, inner, fill=1, stroke=0)

    # Score text in center
    c.setFillColor(HexColor("#0f172a"))
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(cx, cy - 6, f"{score}%")

    # Label below
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#64748b"))
    c.drawCentredString(cx, cy - outer - 14, label)

    # Reset fill color
    c.setFillColor(HexColor("#000000"))


def _draw_horizontal_bar(c, x, y, width, value, max_val, label, color="#14b8a6"):
    """Draw a labeled horizontal progress bar."""
    bar_height = 10
    bg_color = HexColor("#e5e7eb")
    fill_color = HexColor(color)

    # Label
    c.setFont("Helvetica", 10)
    c.setFillColor(HexColor("#0f172a"))
    c.drawString(x, y + 14, f"{label}: {value}/{max_val}")

    # Background bar
    c.setFillColor(bg_color)
    c.roundRect(x, y, width, bar_height, 5, fill=1, stroke=0)

    # Fill bar
    fill_width = (value / max_val) * width if max_val > 0 else 0
    if fill_width > 0:
        c.setFillColor(fill_color)
        c.roundRect(x, y, fill_width, bar_height, 5, fill=1, stroke=0)

    c.setFillColor(HexColor("#000000"))
    return y - 36


def _safe_page(c, y, needed=60):
    """Start a new page if remaining space is insufficient."""
    if y < needed:
        c.showPage()
        c.setFont("Helvetica", 11)
        y = A4[1] - 50
    return y


def generate_pdf(data, filename):
    """
    Generate a full analysis report PDF matching result.html content.

    Expected data keys:
        role, ats_score, matched_skills, missing_skills, roadmap,
        ats_breakdown (dict: skill_score, keyword_score, completeness_score),
        jd_result (dict: match_percentage, matched_skills, missing_keywords),
        insights (dict: length, skill_density, strength, missing_sections),
        suggestions (list of strings),
        missing_classified (dict: critical, optional)
    """
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    y = height - 50

    # ── Title ──
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "Resume Analysis Report")
    y -= 22
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#64748b"))
    c.drawString(50, y, "Generated by ResumeIQ")
    c.setFillColor(HexColor("#000000"))
    y -= 30

    # ── Predicted Role ──
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, f"Predicted Role: {data.get('role', 'N/A')}")
    y -= 35

    # ── ATS Donut Chart ──
    chart_cx = width / 2
    chart_cy = y - 40
    _draw_donut_chart(c, chart_cx, chart_cy, 40, data.get("ats_score", 0))
    y = chart_cy - 65

    # ── ATS Score Breakdown ──
    y = _safe_page(c, y, 140)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "ATS Score Breakdown")
    y -= 24

    breakdown = data.get("ats_breakdown", {})
    skill_sc = breakdown.get("skill_score", 0)
    kw_sc = breakdown.get("keyword_score", 0)
    comp_sc = breakdown.get("completeness_score", 0)

    y = _draw_horizontal_bar(c, 70, y, 300, skill_sc, 50, "Skills Match", "#14b8a6")
    y = _draw_horizontal_bar(c, 70, y, 300, kw_sc, 30, "Keyword Coverage", "#6366f1")
    y = _draw_horizontal_bar(c, 70, y, 300, comp_sc, 20, "Resume Completeness", "#f59e0b")
    y -= 10

    # ── Skills ──
    y = _safe_page(c, y, 100)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Matched Skills:")
    y -= 18

    c.setFont("Helvetica", 10)
    matched = data.get("matched_skills", [])
    if matched:
        skills_line = ", ".join(matched)
        # Word wrap
        for line in _wrap(skills_line, 90):
            y = _safe_page(c, y)
            c.drawString(70, y, line)
            y -= 14
    else:
        c.drawString(70, y, "None detected")
        y -= 14

    y -= 8
    y = _safe_page(c, y, 80)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Missing Skills:")
    y -= 18

    c.setFont("Helvetica", 10)
    missing_classified = data.get("missing_classified", {})
    critical = missing_classified.get("critical", [])
    optional = missing_classified.get("optional", [])

    if critical:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(70, y, "Critical:")
        y -= 14
        c.setFont("Helvetica", 10)
        for skill in critical[:8]:
            y = _safe_page(c, y)
            c.drawString(85, y, f"• {skill}")
            y -= 13

    if optional:
        y -= 4
        c.setFont("Helvetica-Bold", 10)
        c.drawString(70, y, "Optional:")
        y -= 14
        c.setFont("Helvetica", 10)
        for skill in optional[:6]:
            y = _safe_page(c, y)
            c.drawString(85, y, f"• {skill}")
            y -= 13

    if not critical and not optional:
        missing = data.get("missing_skills", [])
        if missing:
            for skill in missing[:8]:
                y = _safe_page(c, y)
                c.drawString(70, y, f"• {skill}")
                y -= 13
        else:
            c.drawString(70, y, "No missing skills detected ✓")
            y -= 14

    # ── JD Match ──
    y -= 10
    y = _safe_page(c, y, 80)
    jd = data.get("jd_result", {})
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Job Description Match")
    y -= 20

    c.setFont("Helvetica", 10)
    match_pct = jd.get("match_percentage", 0)
    c.drawString(70, y, f"Match Percentage: {match_pct}%")
    y -= 16

    jd_matched = jd.get("matched_skills", [])
    if jd_matched:
        c.drawString(70, y, f"Matched: {', '.join(jd_matched[:8])}")
        y -= 16

    jd_missing = jd.get("missing_keywords", [])
    if jd_missing:
        c.drawString(70, y, f"Missing: {', '.join(jd_missing[:8])}")
        y -= 16

    # ── Resume Insights ──
    y -= 10
    y = _safe_page(c, y, 100)
    insights = data.get("insights", {})
    if insights:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Resume Insights")
        y -= 20

        c.setFont("Helvetica", 10)
        c.drawString(70, y, f"Length Analysis: {insights.get('length', 'N/A')}")
        y -= 16
        c.drawString(70, y, f"Skill Density: {insights.get('skill_density', 'N/A')}")
        y -= 16
        c.drawString(70, y, f"Overall Strength: {insights.get('strength', 'N/A')}")
        y -= 16

        ms = insights.get("missing_sections", [])
        if ms:
            c.drawString(70, y, f"Missing Sections: {', '.join(ms)}")
            y -= 16
        else:
            c.drawString(70, y, "All important sections present ✓")
            y -= 16

    # ── AI Suggestions ──
    y -= 10
    y = _safe_page(c, y, 80)
    suggestions = data.get("suggestions", [])
    if suggestions:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "AI Resume Improvement Suggestions")
        y -= 20

        c.setFont("Helvetica", 10)
        for s in suggestions[:6]:
            y = _safe_page(c, y)
            for line in _wrap(f"✦ {s}", 88):
                c.drawString(70, y, line)
                y -= 14

    # ── Career Roadmap ──
    y -= 10
    y = _safe_page(c, y, 80)
    roadmap = data.get("roadmap", {})
    if roadmap:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Career Roadmap")
        y -= 20

        c.setFont("Helvetica", 10)
        for month_key, plan in roadmap.items():
            y = _safe_page(c, y, 40)
            c.setFont("Helvetica-Bold", 10)
            c.drawString(70, y, f"{month_key}:")
            y -= 14
            c.setFont("Helvetica", 9)
            for line in _wrap(plan, 85):
                y = _safe_page(c, y)
                c.drawString(85, y, line)
                y -= 13
            y -= 4

    c.save()


def _wrap(text, max_chars=90):
    """Simple word-wrap utility."""
    words = text.split()
    lines = []
    current = ""
    for w in words:
        if len(current) + len(w) + 1 > max_chars:
            lines.append(current)
            current = w
        else:
            current = f"{current} {w}" if current else w
    if current:
        lines.append(current)
    return lines
